services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: go_app
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=my_pass
      - DB_NAME=postgres
    depends_on:
      - postgres
    restart: unless-stopped